strain_id_field: "accession"
files:
    exclude: "defaults/dropped_strains.txt"
    reference: "defaults/rabies_reference.gb"
    colors: "defaults/colors.tsv"
    auspice_config: "defaults/auspice_config.json"
    description: "defaults/description.md"
    clades: "defaults/clades.tsv"
filter:
    group_by: "country year"
    sequences_per_group: 20
    min_date: 1950
    min_length: 5000
ancestral:
    inference: "joint"
