strain_id_field: "accession"
files:
    exclude: "defaults/dropped_strains.txt"
    reference: "defaults/rabies_reference.gb"
# do not have to dig through the workflows to figure out the default values
filter:
    group_by: "country year"
    sequences_per_group: 20
    min_date: 1950
    min_length: 5000
ancestral:
    inference: "joint"
